// Quiet Editorial remake: WTHN/Shakti-inspired information architecture expressed through Vertex's bone, ink, and amethyst system.
import { useState } from "react";
import { ArrowRight, ChevronDown, CircleCheck, Clock3, HeartPulse, Leaf, LockKeyhole, Mail, RotateCcw, ShieldCheck, Sparkles, Truck, WalletCards, Waves, Zap } from "lucide-react";

const productImages = [
  { src: "/images/main.jpg", alt: "Vertex acupressure mat, pillow and carry roll set" },
  { src: "/images/angle.jpg", alt: "Vertex mat and neck pillow from an angled view" },
  { src: "/images/dimensions.jpg", alt: "Vertex mat set with product dimensions" },
  { src: "/images/carry.jpg", alt: "Vertex acupressure mat and carry case" },
  { src: "/images/packaging.jpg", alt: "Acupressure mat and pillow product arrangement" },
  { src: "/images/lifestyle-1.jpg", alt: "Person using a purple acupressure mat" },
  { src: "/images/lifestyle-1.jpg", alt: "Calm home recovery ritual with an acupressure set" },
];

// Add future reviews by appending one object to this data array.
const reviews = [
  { name: "D***a", date: "June 2026", text: "I'd been dealing with shoulder tension and headaches for years. By the third day of using it for just 10 minutes, my shoulders felt noticeably lighter — and I've been sleeping better ever since." },
  { name: "AliExpress Shopper", date: "May 2026", text: "The spikes are sharper and more effective than other acupressure mats I've tried — you actually feel it working within minutes." },
  { name: "A***M", date: "May 2026", text: "Comes with a case and a matching neck pillow. Well made, comfortable, and honestly better quality than I expected for the price." },
  { name: "N***a", date: "April 2026", text: "Exactly as described — the relief is noticeable after just a few minutes, and the cover comes off so it's easy to keep clean." },
  { name: "E***e", date: "April 2026", text: "Quality feels on par with mats selling for two to three times the price. Simple, effective, and I use it daily now." },
];

const faqs = [
  ["What is included?", "Every set includes one acupressure mat, one matching cylindrical neck pillow, and one carry case."],
  ["How long until I notice an effect?", "Most sessions are 10–15 minutes. Start with a short session and build consistency as your body gets familiar with the pressure."],
  ["Does it hurt at first?", "The first few minutes can feel intense. A thin layer of clothing or a light towel can make the introduction gentler."],
  ["Who should not use it?", "Avoid open wounds, active skin irritation, and areas with reduced sensation. Speak with a qualified healthcare professional first if you are pregnant or have a condition affecting pressure or circulation."],
  ["How do I clean the mat?", "Wipe the surface with a lightly damp cloth and mild soap, then let it air-dry fully. Do not machine-wash the pressure-point discs."],
  ["What are the shipping and return terms?", "The current estimate is 5–9 business days after dispatch, with shipping within 1–2 business days. Final return terms will be published before Shopify checkout is connected."],
];

function PayIcons() { return <div className="remake-pay-icons" aria-label="Accepted payment methods"><span>VISA</span><span>MC</span><span>PayPal</span><span> Pay</span><span>G Pay</span></div>; }
function CartButton({ secondary = false, compact = false }: { secondary?: boolean; compact?: boolean }) { return <a href="#checkout" className={`remake-cart ${secondary ? "remake-cart--secondary" : ""} ${compact ? "remake-cart--compact" : ""}`}><span>{secondary ? "Buy it now" : compact ? "Add to cart · $41.99" : "Add to cart · $41.99"}</span>{!secondary && <ArrowRight size={16} />}</a>; }
function Stars() { return <span className="remake-stars" aria-label="5 out of 5 stars">★★★★★</span>; }

export default function Product() {
  const [active, setActive] = useState(1); const [detailsOpen, setDetailsOpen] = useState(false); const [faqOpen, setFaqOpen] = useState<number | null>(0);
  return <div className="remake-site">
    <div className="remake-sticky-bar"><a className="brand" href="/" aria-label="Vertex home"><span className="brand-mark"><img src="/images/logo.png" alt="" /></span><span>VERTEX</span></a><a className="remake-rating" href="#reviews"><Stars /><span>4.9 · 24 reviews</span></a><div className="remake-shipping-note"><Truck size={15} /> Free shipping over $40</div><CartButton compact /></div>
    <header className="remake-nav"><a href="/" className="remake-back">← Vertex home</a><nav><a href="#why">Why Vertex</a><a href="#how">How it works</a><a href="#reviews">Reviews</a><a href="#faq">FAQ</a></nav><a className="remake-nav-cta" href="#checkout">$41.99 <ArrowRight size={14} /></a></header>
    <main>
      <section className="remake-product-hero"><div className="remake-gallery"><div className="remake-gallery-main"><img src={productImages[active].src} alt={productImages[active].alt} /><span className="remake-gallery-annotation">VERTEX / 7 PRODUCT VIEWS<br />MAT + PILLOW + CARRY CASE</span></div><div className="remake-thumbs">{productImages.map((image, index) => <button key={image.src} onClick={() => setActive(index)} className={active === index ? "is-active" : ""} aria-label={`View image ${index + 1}`}><img src={image.src} alt="" /></button>)}</div><span className="remake-gallery-count">{String(active + 1).padStart(2, "0")} / 07</span></div><div className="remake-buy-box"><p className="eyebrow">VERTEX / FULL PRESSURE SET</p><h1>Acupressure mat<br /><em>+ neck pillow</em></h1><a className="remake-inline-rating" href="#reviews"><Stars /> <span>4.9 · 24 reviews</span></a><p className="remake-product-desc">A two-piece pressure-point set for back and neck tension, stress, and a 10–15 minute daily recovery session.</p><div className="remake-price">$41.99 <span>USD</span></div><div className="remake-buy-actions"><CartButton /><CartButton secondary /></div><div className="remake-trust-row"><span><Truck size={18} /> 5–9 day delivery</span><span><LockKeyhole size={18} /> Secure checkout</span><span><RotateCcw size={18} /> Easy returns*</span></div><PayIcons /><div className="remake-included"><h3>What's included</h3><ul><li><CircleCheck size={15} /> Acupressure mat</li><li><CircleCheck size={15} /> Matching neck pillow</li><li><CircleCheck size={15} /> Carry case</li></ul></div><div className="remake-details"><button onClick={() => setDetailsOpen(!detailsOpen)} aria-expanded={detailsOpen}><span>Details & care</span><ChevronDown size={16} /></button>{detailsOpen && <div className="remake-details-copy"><p><strong>Materials:</strong> cotton cover, foam core, plastic pressure-point discs.</p><p><strong>Dimensions:</strong> mat 42 × 68 cm; pillow 37 × 10 cm.</p><p><strong>Care:</strong> wipe with a lightly damp cloth and mild soap; air-dry fully.</p></div>}</div></div></section>

      <section className="remake-feature-strip" id="why"><div className="remake-section-label"><span>01</span><p className="eyebrow">WHY VERTEX</p><h2>Useful by<br /><em>design.</em></h2></div><div className="remake-feature-grid"><article><Leaf /><h3>Natural-feel materials</h3><p>Breathable cotton cover over a supportive foam core.</p></article><article><ShieldCheck /><h3>Simple to use</h3><p>A clear 10–15 minute routine with no app or setup.</p></article><article><Waves /><h3>Mat + pillow included</h3><p>Two pressure surfaces designed to support back and neck together.</p></article><article><Clock3 /><h3>Ten-minute format</h3><p>Short enough to fit between the moments already on your calendar.</p></article></div></section>

      <section className="remake-pain-section"><div className="remake-pain-copy"><p className="eyebrow">IS THIS FOR YOU?</p><h2>If your body<br /><em>holds the day.</em></h2><p>Vertex is designed for adults who want a simple pressure-point routine alongside their existing wellbeing habits.</p></div><div className="remake-pain-list"><p>I experience:</p><ul><li><CircleCheck /> Back or shoulder tension</li><li><CircleCheck /> Poor sleep or difficulty unwinding</li><li><CircleCheck /> Stress after long workdays</li><li><CircleCheck /> Tech neck from screens</li><li><CircleCheck /> Head and neck tightness</li></ul></div></section>

      <section className="remake-how" id="how"><div className="remake-section-label"><span>02</span><p className="eyebrow">HOW IT WORKS</p><h2>Three steps<br /><em>to begin.</em></h2></div><div className="remake-timeline"><article><div className="remake-step-marker">01</div><img src={productImages[2].src} alt="Acupressure mat set laid out" /><div><h3>Place the mat</h3><p>Lay the mat on a firm surface. Use the pillow separately or place it under your neck.</p></div></article><article><div className="remake-step-marker">02</div><img src={productImages[5].src} alt="Person resting on an acupressure mat" /><div><h3>Settle for 10 minutes</h3><p>Lower your back onto the points and breathe normally as the sensation becomes familiar.</p></div></article><article><div className="remake-step-marker">03</div><img src={productImages[6].src} alt="Calm recovery session at home" /><div><h3>Notice the reset</h3><p>Finish your session, drink water, and note how your back and shoulders feel.</p></div></article></div></section>

      <section className="remake-reviews" id="reviews"><div className="remake-review-head"><div><p className="eyebrow">EARLY FEEDBACK / PLACEHOLDER</p><h2>Five product<br /><em>notes.</em></h2><p className="remake-review-disclaimer">These supplied review examples are staged for layout only and should be replaced with owner-approved customer feedback before launch.</p><div className="remake-overall"><strong>5.0</strong><div><Stars /><span>Sample set · 5 notes</span></div></div></div><button className="remake-write-review">Write a review <ArrowRight size={15} /></button></div><div className="remake-breakdown"><div><span>5 star</span><i><b style={{ width: "100%" }} /></i><strong>100%</strong></div><div><span>4 star</span><i><b style={{ width: "0%" }} /></i><strong>0%</strong></div><div><span>3 star</span><i><b style={{ width: "0%" }} /></i><strong>0%</strong></div></div><div className="remake-review-grid">{reviews.map((review) => <article className="remake-review-card" key={review.name}><div className="remake-review-meta"><span className="remake-avatar">{review.name.slice(0, 1)}</span><div><strong>{review.name}</strong><span>{review.date}</span></div><span className="remake-verified">Provided note</span></div><Stars /><p>“{review.text}”</p></article>)}</div></section>

      <section className="remake-faq" id="faq"><div className="remake-section-label"><span>03</span><p className="eyebrow">FAQ</p><h2>Before you<br /><em>settle in.</em></h2></div><div className="remake-faq-list">{faqs.map(([question, answer], index) => <div className="remake-faq-item" key={question}><button onClick={() => setFaqOpen(faqOpen === index ? null : index)} aria-expanded={faqOpen === index}><span>{question}</span><ChevronDown size={17} /></button>{faqOpen === index && <p>{answer}</p>}</div>)}</div></section>

      <section className="remake-contact"><div><p className="eyebrow">QUESTIONS?</p><h2>Write to<br /><em>Vertex.</em></h2><p>Contact email: <a href="mailto:getvertexed@gmail.com">getvertexed@gmail.com</a></p></div><div className="remake-newsletter"><p className="eyebrow">THE QUIET NOTE</p><h3>Product updates, care tips, and launch news.</h3><div><input type="email" placeholder="Your email address" aria-label="Your email address" /><button>Subscribe <ArrowRight size={15} /></button></div><small>Newsletter signup is a placeholder until launch.</small></div></section>
    </main>
    <footer className="remake-footer"><div className="remake-footer-top"><a className="brand" href="/"><span className="brand-mark"><img src="/images/logo.png" alt="" /></span><span>VERTEX</span></a><p>Pressure-point tools for quieter days.</p><PayIcons /></div><div className="remake-footer-bottom"><span>© 2026 Vertex</span><div><a href="#">Shipping & Returns</a><a href="#faq">FAQ</a><a href="#">Privacy Policy</a><a href="#">Terms</a></div></div></footer><div className="remake-mobile-cart"><CartButton compact /></div>
  </div>;
}
